import { Component } from '@angular/core';
import { ConfigurableCrudConfig, ConfigurableCrudOption, ConfigurableCrudPageBase, ConfigurableCrudRecord, CONFIGURABLE_CRUD_IMPORTS } from '../../../shared/crud/configurable-crud/configurable-crud-page-base';
const yesNo: ConfigurableCrudOption[] = [{ value: 1, label: 'Yes' }, { value: 0, label: 'No' }];
const config: ConfigurableCrudConfig = {
  endpoint: 'support/teams', uuidField: 'SupportTeamUUID', pageTitle: 'Support teams', pageDescription: 'Manage teams responsible for tenant support work.', createTitle: 'New support team', editTitle: 'Edit support team', dialogDescription: 'Maintain the support team capacity and queue settings.', searchPlaceholder: 'Search', emptyLabel: 'No support teams found.', deleteTitle: 'Delete support team', deleteMessage: 'Delete this support team?', deleteSelectedTitle: 'Delete selected support teams', deleteSelectedMessage: 'Delete {count} selected support teams?', savedMessage: 'Support team saved successfully.', deletedMessage: 'Support team deleted successfully.', deleteFailedMessage: 'Failed to delete support team.', statusMode: 'number', activeValue: 1, inactiveValue: 0, bulkDelete: false,
  initialValues: { status: 1, isDefault: 0, name: '', code: '', queuePriority: 0, maxConcurrentTickets: 0, description: '' },
  columns: [{ id: 'name', label: 'Name', kind: 'identity', field: 'Name', uuidField: 'SupportTeamUUID' }, { id: 'code', label: 'Code', field: 'Code' }, { id: 'members', label: 'Members', field: 'MembersCount' }, { id: 'default', label: 'Default', kind: 'boolean', field: 'IsDefault' }, { id: 'status', label: 'Status', kind: 'status', field: 'Status' }],
  fields: [{ key: 'status', source: 'Status', type: 'status', label: 'Status', span: 1 }, { key: 'isDefault', source: 'IsDefault', type: 'select', options: yesNo, label: 'Default team', span: 1 }, { key: 'name', source: 'Name', label: 'Name', required: true, span: 1 }, { key: 'code', source: 'Code', label: 'Code', span: 1 }, { key: 'queuePriority', source: 'QueuePriority', type: 'number', label: 'Queue priority', span: 1 }, { key: 'maxConcurrentTickets', source: 'MaxConcurrentTickets', type: 'number', label: 'Maximum concurrent tickets', span: 1 }, { key: 'description', source: 'Description', type: 'textarea', tab: 'notes', label: 'Description', span: 4, rows: 4 }],
};
@Component({ selector: 'app-support-teams', standalone: true, imports: CONFIGURABLE_CRUD_IMPORTS, templateUrl: '../../../shared/crud/configurable-crud/configurable-crud-page.html', styleUrls: ['../../../shared/crud/configurable-crud/configurable-crud-page.scss'] })
export class SupportTeamsPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> { constructor() { super(config); } protected override augmentPayload(payload: ConfigurableCrudRecord) { return { ...payload, status: Number(payload['status']), isDefault: Number(payload['isDefault']), queuePriority: Number(payload['queuePriority']), maxConcurrentTickets: Number(payload['maxConcurrentTickets']) }; } }
