import { Component } from '@angular/core';
import { ConfigurableCrudConfig, ConfigurableCrudPageBase, ConfigurableCrudRecord, CONFIGURABLE_CRUD_IMPORTS } from '../../../shared/crud/configurable-crud/configurable-crud-page-base';
const config: ConfigurableCrudConfig = {
  endpoint: 'support/ticket-channels', uuidField: 'SupportTicketChannelUUID', pageTitle: 'Ticket channels', pageDescription: 'Manage tenant channels used to classify support tickets.', createTitle: 'New ticket channel', editTitle: 'Edit ticket channel', dialogDescription: 'Maintain the ticket channel catalog.', searchPlaceholder: 'Search', emptyLabel: 'No ticket channels found.', deleteTitle: 'Delete ticket channel', deleteMessage: 'Delete this ticket channel?', deleteSelectedTitle: 'Delete selected ticket channels', deleteSelectedMessage: 'Delete {count} selected ticket channels?', savedMessage: 'Ticket channel saved successfully.', deletedMessage: 'Ticket channel deleted successfully.', deleteFailedMessage: 'Failed to delete ticket channel.', statusMode: 'number', activeValue: 1, inactiveValue: 0, bulkDelete: false,
  initialValues: { status: 1, name: '', code: '', description: '' },
  columns: [{ id: 'name', label: 'Name', kind: 'identity', field: 'Name', uuidField: 'SupportTicketChannelUUID' }, { id: 'code', label: 'Code', field: 'Code' }, { id: 'description', label: 'Description', field: 'Description' }, { id: 'status', label: 'Status', kind: 'status', field: 'Status' }],
  fields: [{ key: 'status', source: 'Status', type: 'status', label: 'Status', span: 1 }, { key: 'name', source: 'Name', label: 'Name', required: true, span: 1 }, { key: 'code', source: 'Code', label: 'Code', span: 1 }, { key: 'description', source: 'Description', type: 'textarea', label: 'Description', tab: 'notes', span: 4, rows: 4 }],
};
@Component({ selector: 'app-support-ticket-channels', standalone: true, imports: CONFIGURABLE_CRUD_IMPORTS, templateUrl: '../../../shared/crud/configurable-crud/configurable-crud-page.html', styleUrls: ['../../../shared/crud/configurable-crud/configurable-crud-page.scss'] })
export class SupportTicketChannelsPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> { constructor() { super(config); } }
