export type VoipSoftswitchDidItem = {
  VsdUUID: string;
  VsdID: string;
  VoipSoftswitchAccountVssUUID: string;
  CustomerCusUUID: string;
  VoipDomainVdmUUID: string;
  VoipDidVddUUID: string;
  VoipSoftswitchSubscriberVsuUUID?: string | null;
  VoipSoftswitchTrunkVtkUUID?: string | null;
  VsdNumber: string;
  VsdDirection: 'inbound' | 'outbound' | 'both';
  VsdRouteType: 'subscriber' | 'external' | 'trunk' | 'none';
  VsdRouteValue?: string | null;
  VsdDescription?: string | null;
  VsdEnabled: number;
  SoftswitchName?: string | null;
  CustomerName?: string | null;
  DomainName?: string | null;
  SubscriberUsername?: string | null;
  TrunkName?: string | null;
  DidOrigin?: 'MNSCLOUD' | 'EXTERNAL' | string | null;
  DidValidationStatus?: string | null;
  DidBillingStatus?: string | null;
};
