import { CRM_OPTIONS } from '../crm-options';
import { crmPayload, crmLocalDate, crmLocalTime } from '../crm-input';
import { Component } from '@angular/core';
import {
  CONFIGURABLE_CRUD_IMPORTS,
  ConfigurableCrudPageBase,
  ConfigurableCrudRecord,
} from '../../../shared/crud/configurable-crud/configurable-crud-page-base';
import { defineCrud } from '../../../shared/crud/configurable-crud/define-crud';
import { crmActions } from '../crm-actions';
const config = defineCrud({
  endpoint: 'crm/opportunities',
  uuidField: 'CopUUID',
  pageTitle: 'crm.title.opportunities',
  defaultCurrencyFields: ['CopCurrency'],
  initialValues: {
    CopName: '',
    CrmAccountCacUUID: '',
    CrmContactCcoUUID: '',
    CrmStageCstUUID: '',
    CrmProductCprUUID: '',
    CrmSourceCsoUUID: '',
    CrmLossReasonClrUUID: '',
    CopNeed: '',
    CopNextContactAt: '',
    CopExpectedClose: '',
    CopAmountOnce: 0,
    CopAmountRecurring: 0,
    CopCurrency: '',
    CopPeriod: 'monthly',
    CopEvidence: '',
    CopStatus: 1,
    AssignedUserUsrUUID: '',
  },
  fields: [
    {
      key: 'CopStatus',
      source: 'CopStatus',
      label: 'crm.field.Status',
      span: 1,
      required: true,
      type: 'status',
    },
    {
      key: 'CrmStageCstUUID',
      source: 'CrmStageCstUUID',
      label: 'crm.title.stages',
      span: 1,
      required: true,
      type: 'search-select',
      remoteLookup: {
        selectedLabelField: 'CrmStageCstUUIDName',
        endpoint: 'crm/stages',
        uuidField: 'CstUUID',
        labelField: 'CstName',
      },
    },
    {
      key: 'CrmSourceCsoUUID',
      source: 'CrmSourceCsoUUID',
      label: 'crm.title.sources',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        selectedLabelField: 'CrmSourceCsoUUIDName',
        endpoint: 'crm/sources',
        uuidField: 'CsoUUID',
        labelField: 'CsoName',
      },
    },
    {
      key: 'AssignedUserUsrUUID',
      source: 'AssignedUserUsrUUID',
      label: 'crm.field.AssignedUserUsrUUID',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        endpoint: 'crm/members',
        uuidField: 'UsrUUID',
        labelField: 'UsrName',
      },
      quickCreate: false,
      quickCreateExemptReason:
        'Assignment selects existing tenant members; membership is managed through the canonical tenant invitation flow.',
    },
    {
      key: 'CopName',
      source: 'CopName',
      label: 'crm.field.Name',
      span: 2,
      required: true,
      type: 'text',
    },
    {
      key: 'CrmAccountCacUUID',
      source: 'CrmAccountCacUUID',
      label: 'crm.title.accounts',
      span: 1,
      required: true,
      type: 'search-select',
      remoteLookup: {
        endpoint: 'crm/accounts',
        uuidField: 'CacUUID',
        labelField: 'CacName',
        selectedLabelField: 'CrmAccountCacUUIDName',
      },
    },
    {
      key: 'CrmContactCcoUUID',
      source: 'CrmContactCcoUUID',
      label: 'crm.title.contacts',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        selectedLabelField: 'CrmContactCcoUUIDName',
        endpoint: 'crm/contacts',
        uuidField: 'CcoUUID',
        labelField: 'CcoName',
      },
    },
    {
      key: 'CrmProductCprUUID',
      source: 'CrmProductCprUUID',
      label: 'crm.title.products',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        selectedLabelField: 'CrmProductCprUUIDName',
        endpoint: 'crm/products',
        uuidField: 'CprUUID',
        labelField: 'CprName',
      },
    },
    {
      key: 'CrmLossReasonClrUUID',
      source: 'CrmLossReasonClrUUID',
      label: 'crm.title.loss-reasons',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        selectedLabelField: 'CrmLossReasonClrUUIDName',
        endpoint: 'crm/loss-reasons',
        uuidField: 'ClrUUID',
        labelField: 'ClrName',
      },
    },
    {
      key: 'CopNextContactAt',
      source: 'CopNextContactAt',
      label: 'crm.field.NextContactAt',
      span: 1,
      required: false,
      type: 'date',
      fromRecord: crmLocalDate,
      breakBefore: true,
      requiredWhen: ({ values }) => Boolean(values['CopNextContactAtTime']),
    },
    {
      key: 'CopNextContactAtTime',
      source: 'CopNextContactAt',
      label: 'Time',
      type: 'time',
      span: 1,
      fromRecord: crmLocalTime,
      requiredWhen: ({ values }) => Boolean(values['CopNextContactAt']),
    },
    {
      key: 'CopExpectedClose',
      source: 'CopExpectedClose',
      label: 'crm.field.ExpectedClose',
      span: 1,
      required: false,
      type: 'date',
    },
    {
      key: 'CopNeed',
      source: 'CopNeed',
      label: 'crm.field.Need',
      span: 4,
      required: false,
      type: 'textarea',
      rows: 4,
      breakBefore: true,
    },
    {
      key: 'CopCurrency',
      source: 'CopCurrency',
      label: 'crm.field.Currency',
      span: 1,
      required: false,
      type: 'text',
      tab: 'financial',
    },
    {
      key: 'CopPeriod',
      source: 'CopPeriod',
      label: 'crm.field.Period',
      span: 1,
      required: true,
      type: 'select',
      translateOptions: true,
      options: CRM_OPTIONS.recurringPeriods,
      tab: 'financial',
    },
    {
      key: 'CopAmountOnce',
      source: 'CopAmountOnce',
      label: 'crm.field.AmountOnce',
      span: 1,
      required: true,
      type: 'currency',
      currencyKey: 'CopCurrency',
      tab: 'financial',
    },
    {
      key: 'CopAmountRecurring',
      source: 'CopAmountRecurring',
      label: 'crm.field.AmountRecurring',
      span: 1,
      required: true,
      type: 'currency',
      currencyKey: 'CopCurrency',
      tab: 'financial',
    },
    {
      key: 'CopEvidence',
      source: 'CopEvidence',
      label: 'crm.field.Evidence',
      span: 4,
      required: false,
      type: 'textarea',
      rows: 4,
      breakBefore: true,
      tab: 'financial',
    },
    { key: 'CopRevision', source: 'CopRevision', label: 'crm.field.Revision', hidden: true },
  ],
  columns: [
    {
      id: 'CrmAccountCacUUID',
      field: 'CrmAccountCacUUIDName',
      label: 'crm.title.accounts',
      kind: 'text',
    },
    {
      id: 'CrmContactCcoUUID',
      field: 'CrmContactCcoUUIDName',
      label: 'crm.title.contacts',
      kind: 'text',
    },
    {
      id: 'CrmStageCstUUID',
      field: 'CrmStageCstUUIDName',
      label: 'crm.title.stages',
      kind: 'text',
    },
    {
      id: 'CrmProductCprUUID',
      field: 'CrmProductCprUUIDName',
      label: 'crm.title.products',
      kind: 'text',
    },
    {
      id: 'CrmSourceCsoUUID',
      field: 'CrmSourceCsoUUIDName',
      label: 'crm.title.sources',
      kind: 'text',
    },
    {
      id: 'CrmLossReasonClrUUID',
      field: 'CrmLossReasonClrUUIDName',
      label: 'crm.title.loss-reasons',
      kind: 'text',
    },
    {
      id: 'CopName',
      field: 'CopName',
      label: 'crm.field.Name',
      kind: 'identity',
    },
    {
      id: 'CopNextContactAt',
      field: 'CopNextContactAt',
      label: 'crm.field.NextContactAt',
      kind: 'datetime',
    },
    {
      id: 'CopAmountOnce',
      field: 'CopAmountOnce',
      label: 'crm.field.AmountOnce',
      kind: 'currency',
      currencyField: 'CopCurrency',
    },
    {
      id: 'CopAmountRecurring',
      field: 'CopAmountRecurring',
      label: 'crm.field.AmountRecurring',
      kind: 'currency',
      currencyField: 'CopCurrency',
    },
    {
      id: 'CopPeriod',
      field: 'CopPeriod',
      label: 'crm.field.Period',
      kind: 'text',
      options: CRM_OPTIONS.recurringPeriods,
    },
    {
      id: 'CopStatus',
      field: 'CopStatus',
      label: 'crm.field.Status',
      kind: 'status',
    },
  ],
  listFilters: [
    {
      key: 'CrmAccountCacUUID',
      paramKey: 'CrmAccountCacUUID',
      label: 'crm.title.accounts',
      type: 'search-select',
      span: 1,
      remoteLookup: { endpoint: 'crm/accounts', uuidField: 'CacUUID', labelField: 'CacName' },
    },
    {
      key: 'CrmContactCcoUUID',
      paramKey: 'CrmContactCcoUUID',
      label: 'crm.title.contacts',
      type: 'search-select',
      span: 1,
      remoteLookup: {
        selectedLabelField: 'CrmContactCcoUUIDName',
        endpoint: 'crm/contacts',
        uuidField: 'CcoUUID',
        labelField: 'CcoName',
      },
    },
    {
      key: 'CrmStageCstUUID',
      paramKey: 'CrmStageCstUUID',
      label: 'crm.title.stages',
      type: 'search-select',
      span: 1,
      remoteLookup: {
        selectedLabelField: 'CrmStageCstUUIDName',
        endpoint: 'crm/stages',
        uuidField: 'CstUUID',
        labelField: 'CstName',
      },
    },
    {
      key: 'CrmProductCprUUID',
      paramKey: 'CrmProductCprUUID',
      label: 'crm.title.products',
      type: 'search-select',
      span: 1,
      remoteLookup: {
        selectedLabelField: 'CrmProductCprUUIDName',
        endpoint: 'crm/products',
        uuidField: 'CprUUID',
        labelField: 'CprName',
      },
    },
    {
      key: 'CrmSourceCsoUUID',
      paramKey: 'CrmSourceCsoUUID',
      label: 'crm.title.sources',
      type: 'search-select',
      span: 1,
      remoteLookup: {
        selectedLabelField: 'CrmSourceCsoUUIDName',
        endpoint: 'crm/sources',
        uuidField: 'CsoUUID',
        labelField: 'CsoName',
      },
    },
    {
      key: 'CrmLossReasonClrUUID',
      paramKey: 'CrmLossReasonClrUUID',
      label: 'crm.title.loss-reasons',
      type: 'search-select',
      span: 1,
      remoteLookup: {
        selectedLabelField: 'CrmLossReasonClrUUIDName',
        endpoint: 'crm/loss-reasons',
        uuidField: 'ClrUUID',
        labelField: 'ClrName',
      },
    },
    {
      key: 'AssignedUserUsrUUID',
      paramKey: 'AssignedUserUsrUUID',
      label: 'crm.field.AssignedUserUsrUUID',
      type: 'search-select',
      span: 1,
      remoteLookup: { endpoint: 'crm/members', uuidField: 'UsrUUID', labelField: 'UsrName' },
    },
    {
      key: 'CopPeriod',
      paramKey: 'CopPeriod',
      label: 'crm.field.Period',
      type: 'select',
      translateOptions: true,
      options: CRM_OPTIONS.recurringPeriods,
      span: 1,
    },
  ],
  serverSidePagination: true,
  // CRM deletion is individually audited; see app.md, CRM form baseline.
  bulkDelete: false,
  canEditRow: (row) => row['StageKind'] === 'open',
  quickCreateLabelField: 'CopName',
  payload: (values, editing) =>
    crmPayload(
      values,
      editing,
      'CopRevision',
      ['CopAmountOnce', 'CopAmountRecurring', 'CopStatus', 'CopRevision'],
      ['CopNextContactAt'],
    ),
  rowActions: crmActions('opportunities'),
});
@Component({
  selector: 'app-crm-opportunities',
  standalone: true,
  imports: CONFIGURABLE_CRUD_IMPORTS,
  templateUrl: '../../../shared/crud/configurable-crud/configurable-crud-page.html',
  styleUrls: ['../../../shared/crud/configurable-crud/configurable-crud-page.scss'],
})
export class CrmOpportunityPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> {
  constructor() {
    super(config);
  }
}
