// Sidebar navigation registry. Data only: the Navigation Label Contract in app.md governs every
// label and `npm run check:nav` enforces it. Labels are `nav.<id>` keys (id with `/` -> `.`)
// translated in public/i18n/{en-US,pt-BR,es-ES}.json; never reuse shared CRUD keys here.

export type MenuScope = 'public' | 'tenant' | 'master' | 'both';

export interface NavItem {
  id: string;
  /** Transloco key, always `nav.<id>` with `/` replaced by `.`. */
  label: string;
  icon?: string;
  route?: string;
  masterRoute?: string;
  scope?: MenuScope;
  entitlementCode?: string;
  children?: NavItem[];

  permissions?: string[];

  // ✅ Controle de visibilidade por TENANT (exige EnvironmentUUID selecionado)
  requiresEnvironment?: boolean;
}

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', label: 'nav.dashboard', icon: 'dashboard', route: '/dashboard' },
  {
    id: 'billing',
    label: 'nav.billing',
    icon: 'account_balance_wallet',
    children: [
      {
        id: 'billing/dashboard',
        label: 'nav.billing.dashboard',
        icon: 'dashboard',
        route: '/billing',
        masterRoute: '/system/billing',
      },
      {
        id: 'billing/catalog-products',
        label: 'nav.billing.catalog-products',
        icon: 'storefront',
        route: '/billing/catalog',
        masterRoute: '/system/billing/products',
      },
      {
        id: 'billing/prices',
        label: 'nav.billing.prices',
        icon: 'sell',
        masterRoute: '/system/billing/prices',
      },
      {
        id: 'billing/packages',
        label: 'nav.billing.packages',
        icon: 'redeem',
        masterRoute: '/system/billing/packages',
      },
      {
        id: 'billing/promotions',
        label: 'nav.billing.promotions',
        icon: 'local_offer',
        masterRoute: '/system/billing/promotions',
      },
      {
        id: 'billing/subscriptions',
        label: 'nav.billing.subscriptions',
        icon: 'subscriptions',
        route: '/billing/subscriptions',
        masterRoute: '/system/billing/subscriptions',
      },
      {
        id: 'billing/topups',
        label: 'nav.billing.topups',
        icon: 'add_card',
        route: '/billing/topups',
        requiresEnvironment: true,
      },
      {
        id: 'billing/ledger-wallets',
        label: 'nav.billing.ledger-wallets',
        icon: 'receipt_long',
        route: '/billing/ledger',
        masterRoute: '/system/billing/wallets',
      },
    ],
  },

  {
    id: 'user',
    label: 'nav.user',
    icon: 'person',
    children: [
      { id: 'user/profile', label: 'nav.user.profile', icon: 'badge', route: '/user/profile' },
      {
        id: 'user/permission-management',
        label: 'nav.user.permission-management',
        icon: 'admin_panel_settings',
        permissions: ['tenant.permissions.manage'],
        children: [
          {
            id: 'user/access-profiles',
            label: 'nav.user.access-profiles',
            icon: 'groups',
            route: '/user/access-profiles',
          },
          {
            id: 'user/special-permissions',
            label: 'nav.user.special-permissions',
            icon: 'verified_user',
            route: '/user/permissions',
          },
        ],
      },
      {
        id: 'user/api-tokens',
        label: 'nav.user.api-tokens',
        icon: 'vpn_key',
        route: '/user/api-tokens',
        scope: 'tenant',
        permissions: ['tenant.security.api-tokens.manage'],
        requiresEnvironment: true,
      },
      {
        id: 'user/governance',
        label: 'nav.user.governance',
        icon: 'manage_accounts',
        masterRoute: '/system/governance/users',
      },
    ],
  },

  {
    id: 'system/pay',
    label: 'nav.system.pay',
    icon: 'credit_card',
    scope: 'master',
    children: [
      {
        id: 'system/pay/bank-partners',
        label: 'nav.system.pay.bank-partners',
        icon: 'account_balance',
        masterRoute: '/system/pay/bank-partners',
      },
      {
        id: 'system/pay/fees',
        label: 'nav.system.pay.fees',
        icon: 'percent',
        children: [
          {
            id: 'system/pay/fee-plans',
            label: 'nav.system.pay.fee-plans',
            icon: 'sell',
            masterRoute: '/system/pay/fee-plans',
          },
          {
            id: 'system/pay/fee-plan-assignments',
            label: 'nav.system.pay.fee-plan-assignments',
            icon: 'assignment_ind',
            masterRoute: '/system/pay/fee-plan-assignments',
          },
          {
            id: 'system/pay/fee-accruals',
            label: 'nav.system.pay.fee-accruals',
            icon: 'pending_actions',
            masterRoute: '/system/pay/fee-accruals',
          },
        ],
      },
    ],
  },

  // ✅ ERP (tenant; plataforma usa rotas globais quando disponível)
  {
    id: 'erp',
    label: 'nav.erp',
    icon: 'apps',
    entitlementCode: 'module.erp.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'erp/registration',
        label: 'nav.erp.registration',
        icon: 'assignment',
        children: [
          {
            id: 'erp/companies',
            label: 'nav.erp.companies',
            icon: 'apartment',
            route: '/erp/companies',
          },
          { id: 'erp/customer', label: 'nav.erp.customer', icon: 'person', route: '/erp/customer' },
          {
            id: 'erp/supplier',
            label: 'nav.erp.supplier',
            icon: 'inventory_2',
            route: '/erp/supplier',
          },
          {
            id: 'erp/carrier',
            label: 'nav.erp.carrier',
            icon: 'local_shipping',
            route: '/erp/carrier',
          },
          {
            id: 'erp/reseller',
            label: 'nav.erp.reseller',
            icon: 'storefront',
            route: '/erp/reseller',
          },
          {
            id: 'erp/complex',
            label: 'nav.erp.complex',
            icon: 'location_city',
            route: '/erp/complex',
          },
        ],
      },
      {
        id: 'erp/financial',
        label: 'nav.erp.financial',
        icon: 'account_balance',
        children: [
          {
            id: 'erp/financial/accounts',
            label: 'nav.erp.financial.accounts',
            icon: 'account_balance_wallet',
            children: [
              {
                id: 'erp/financial/account/payables',
                label: 'nav.erp.financial.account.payables',
                icon: 'payments',
                route: '/erp/financial/account/payables',
              },
              {
                id: 'erp/financial/account/receivables',
                label: 'nav.erp.financial.account.receivables',
                icon: 'receipt_long',
                route: '/erp/financial/account/receivables',
              },
            ],
          },
          {
            id: 'erp/financial/payment',
            label: 'nav.erp.financial.payment',
            icon: 'payments',
            children: [
              {
                id: 'erp/financial/payment-gateway',
                label: 'nav.erp.financial.payment-gateway',
                icon: 'credit_card',
                route: '/erp/financial/payment-gateway',
              },
              {
                id: 'erp/financial/payment-method',
                label: 'nav.erp.financial.payment-method',
                icon: 'tune',
                route: '/erp/financial/payment-method',
              },
            ],
          },
        ],
      },
      {
        id: 'erp/financial/invoicing',
        label: 'nav.erp.financial.invoicing',
        icon: 'receipt_long',
        children: [
          {
            id: 'erp/financial/invoicing/boletos',
            label: 'nav.erp.financial.invoicing.boletos',
            icon: 'receipt',
            route: '/erp/financial/invoicing/boletos',
          },
          {
            id: 'erp/financial/invoicing/invoices',
            label: 'nav.erp.financial.invoicing.invoices',
            icon: 'request_quote',
            route: '/erp/financial/invoicing/invoices',
          },
          {
            id: 'erp/financial/invoicing/contracts',
            label: 'nav.erp.financial.invoicing.contracts',
            icon: 'description',
            route: '/erp/financial/invoicing/contracts',
          },
          {
            id: 'erp/financial/invoicing/duedays',
            label: 'nav.erp.financial.invoicing.duedays',
            icon: 'event_repeat',
            route: '/erp/financial/invoicing/duedays',
          },
        ],
      },
      {
        id: 'erp/human-resources',
        label: 'nav.erp.human-resources',
        icon: 'groups',
        children: [
          {
            id: 'erp/human-resources/employees',
            label: 'nav.erp.human-resources.employees',
            icon: 'badge',
            route: '/erp/human-resources/employees',
          },
          {
            id: 'erp/human-resources/time-clock-accounts',
            label: 'nav.erp.human-resources.time-clock-accounts',
            icon: 'schedule',
            route: '/erp/human-resources/time-clock-accounts',
          },
          {
            id: 'erp/human-resources/departments',
            label: 'nav.erp.human-resources.departments',
            icon: 'account_tree',
            route: '/erp/human-resources/departments',
          },
          {
            id: 'erp/human-resources/positions',
            label: 'nav.erp.human-resources.positions',
            icon: 'work',
            route: '/erp/human-resources/positions',
          },
        ],
      },
    ],
  },

  // ✅ ISP (tenant; plataforma usa rotas globais quando disponível)
  {
    id: 'isp',
    label: 'nav.isp',
    icon: 'network_check',
    entitlementCode: 'module.isp.*',
    requiresEnvironment: true,
    children: [
      { id: 'isp/pop', label: 'nav.isp.pop', icon: 'location_on', route: '/isp/pop' },
      { id: 'isp/nas', label: 'nav.isp.nas', icon: 'router', route: '/isp/nas' },
      { id: 'isp/olt', label: 'nav.isp.olt', icon: 'settings_input_antenna', route: '/isp/olt' },
      {
        id: 'isp/pool-ip',
        label: 'nav.isp.pool-ip',
        icon: 'lan',
        children: [
          {
            id: 'isp/pool-ip/pool-ipv4',
            label: 'nav.isp.pool-ip.pool-ipv4',
            icon: 'badge',
            route: '/isp/pool-ip/pool-ipv4',
          },
          {
            id: 'isp/pool-ip/pool-ipv6',
            label: 'nav.isp.pool-ip.pool-ipv6',
            icon: 'badge',
            route: '/isp/pool-ip/pool-ipv6',
          },
          {
            id: 'isp/pool-ip/fixed-ipv4',
            label: 'nav.isp.pool-ip.fixed-ipv4',
            icon: 'pin',
            route: '/isp/pool-ip/fixed-ipv4',
          },
          {
            id: 'isp/pool-ip/fixed-ipv6',
            label: 'nav.isp.pool-ip.fixed-ipv6',
            icon: 'pin',
            route: '/isp/pool-ip/fixed-ipv6',
          },
        ],
      },
      {
        id: 'isp/radius-server',
        label: 'nav.isp.radius-server',
        icon: 'security',
        children: [
          {
            id: 'isp/radius-server/registry',
            label: 'nav.isp.radius-server.registry',
            icon: 'badge',
            route: '/isp/radius-server',
            masterRoute: '/system/isp/radius-server',
          },
          {
            id: 'isp/radius-server/pppoe-client',
            label: 'nav.isp.radius-server.pppoe-client',
            icon: 'vpn_key',
            route: '/isp/radius-server/pppoe-client',
          },
        ],
      },
      {
        id: 'isp/vendor',
        label: 'nav.isp.vendor',
        icon: 'factory',
        children: [
          {
            id: 'isp/vendor/registry',
            label: 'nav.isp.vendor.registry',
            icon: 'badge',
            route: '/isp/vendor',
          },
          {
            id: 'isp/vendor/model',
            label: 'nav.isp.vendor.model',
            icon: 'memory',
            route: '/isp/vendor-model',
          },
        ],
      },
    ],
  },

  // ✅ InfraGIS (tenant)
  {
    id: 'infragis',
    label: 'nav.infragis',
    icon: 'map',
    entitlementCode: 'module.infragis.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'infragis/dashboard',
        label: 'nav.infragis.dashboard',
        icon: 'dashboard',
        route: '/infragis',
      },
      {
        id: 'infragis/projects',
        label: 'nav.infragis.projects',
        icon: 'folder',
        route: '/infragis/management/projects',
      },
      {
        id: 'infragis/layers',
        label: 'nav.infragis.layers',
        icon: 'layers',
        route: '/infragis/management/layers',
      },
      {
        id: 'infragis/categories',
        label: 'nav.infragis.categories',
        icon: 'category',
        route: '/infragis/management/categories',
      },
      {
        id: 'infragis/asset-types',
        label: 'nav.infragis.asset-types',
        icon: 'widgets',
        route: '/infragis/management/asset-types',
      },
      {
        id: 'infragis/statuses',
        label: 'nav.infragis.statuses',
        icon: 'flag',
        route: '/infragis/management/statuses',
      },
      {
        id: 'infragis/assets',
        label: 'nav.infragis.assets',
        icon: 'place',
        route: '/infragis/management/assets',
      },
    ],
  },

  // ✅ VoIP (tenant; plataforma usa rotas globais quando disponível)
  {
    id: 'voip',
    label: 'nav.voip',
    icon: 'call',
    entitlementCode: 'module.voip.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'voip/dashboard',
        label: 'nav.voip.dashboard',
        icon: 'dashboard',
        route: '/voip',
        masterRoute: '/system/voip',
        scope: 'both',
      },
      {
        id: 'voip/domains',
        label: 'nav.voip.domains',
        icon: 'language',
        route: '/voip/domains',
        masterRoute: '/system/voip/domains',
        scope: 'both',
      },
      {
        id: 'voip/portability',
        label: 'nav.voip.portability',
        icon: 'swap_horiz',
        entitlementCode: 'module.voip.*',
        children: [
          {
            id: 'voip/portability-orders',
            label: 'nav.voip.portability-orders',
            icon: 'assignment',
            route: '/voip/portability-orders',
          },
          {
            id: 'voip/portability-reasons',
            label: 'nav.voip.portability-reasons',
            icon: 'format_list_bulleted',
            route: '/voip/portability-reasons',
            permissions: ['tenant.access.manage'],
          },
        ],
      },
      {
        id: 'voip/did',
        label: 'nav.voip.did',
        icon: 'dialpad',
        children: [
          {
            id: 'voip/did/dashboard',
            label: 'nav.voip.did.dashboard',
            icon: 'dashboard',
            route: '/voip/did',
            masterRoute: '/system/did',
          },
          {
            id: 'voip/did/operator',
            label: 'nav.voip.did.operator',
            icon: 'badge',
            route: '/voip/did/operator',
            masterRoute: '/system/did/operator',
            permissions: ['platform.master.access'],
          },
          {
            id: 'voip/did/number',
            label: 'nav.voip.did.number',
            icon: 'dialpad',
            route: '/voip/did/number',
            masterRoute: '/system/did/number',
          },
          {
            id: 'voip/did/external',
            label: 'nav.voip.did.external',
            icon: 'add_ic_call',
            route: '/voip/did/external',
            masterRoute: '/system/did/external',
          },
        ],
      },
      {
        id: 'voip/sbc',
        label: 'nav.voip.sbc',
        icon: 'settings_input_component',
        children: [
          {
            id: 'voip/sbc/dashboard',
            label: 'nav.voip.sbc.dashboard',
            icon: 'dashboard',
            route: '/voip/sbc/dashboard',
            masterRoute: '/system/sbc/dashboard',
          },
          {
            id: 'voip/sbc/server',
            label: 'nav.voip.sbc.server',
            icon: 'dns',
            masterRoute: '/system/sbc/server',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'voip/sbc/domains',
            label: 'nav.voip.sbc.domains',
            icon: 'language',
            route: '/voip/sbc/domains',
          },
          {
            id: 'voip/sbc/account',
            label: 'nav.voip.sbc.account',
            icon: 'settings_input_component',
            route: '/voip/sbc/account',
          },
          {
            id: 'voip/sbc/interface',
            label: 'nav.voip.sbc.interface',
            icon: 'settings_input_component',
            masterRoute: '/system/sbc/interface',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'voip/sbc/peer',
            label: 'nav.voip.sbc.peer',
            icon: 'settings_ethernet',
            route: '/voip/sbc/peer',
          },
          {
            id: 'voip/sbc/pipe',
            label: 'nav.voip.sbc.pipe',
            icon: 'schema',
            route: '/voip/sbc/pipe',
          },
          {
            id: 'voip/sbc/manipulation',
            label: 'nav.voip.sbc.manipulation',
            icon: 'transform',
            route: '/voip/sbc/manipulation',
          },
          {
            id: 'voip/sbc/cdr',
            label: 'nav.voip.sbc.cdr',
            icon: 'receipt_long',
            route: '/voip/sbc/cdr',
          },
        ],
      },
      {
        id: 'voip/softswitch',
        label: 'nav.voip.softswitch',
        icon: 'router',
        children: [
          {
            id: 'voip/softswitch/dashboard',
            label: 'nav.voip.softswitch.dashboard',
            icon: 'dashboard',
            route: '/voip/softswitch',
            masterRoute: '/system/softswitch',
          },
          {
            id: 'voip/softswitch/server',
            label: 'nav.voip.softswitch.server',
            icon: 'dns',
            masterRoute: '/system/softswitch/server',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'voip/softswitch/domains',
            label: 'nav.voip.softswitch.domains',
            icon: 'language',
            route: '/voip/softswitch/domains',
            scope: 'tenant',
          },
          {
            id: 'voip/softswitch/accounts',
            label: 'nav.voip.softswitch.accounts',
            icon: 'router',
            route: '/voip/softswitch/accounts',
            scope: 'tenant',
          },
          {
            id: 'voip/softswitch/subscriber',
            label: 'nav.voip.softswitch.subscriber',
            icon: 'person',
            route: '/voip/softswitch/subscriber',
          },
          {
            id: 'voip/softswitch/did',
            label: 'nav.voip.softswitch.did',
            icon: 'tag',
            route: '/voip/softswitch/did',
          },
          {
            id: 'voip/softswitch/trunks',
            label: 'nav.voip.softswitch.trunks',
            icon: 'settings_input_component',
            children: [
              {
                id: 'voip/softswitch/trunks/list',
                label: 'nav.voip.softswitch.trunks.list',
                icon: 'settings_input_component',
                route: '/voip/softswitch/trunks',
              },
              {
                id: 'voip/softswitch/trunk-groups',
                label: 'nav.voip.softswitch.trunk-groups',
                icon: 'hub',
                route: '/voip/softswitch/trunk-groups',
              },
              {
                id: 'voip/softswitch/trunk-group-members',
                label: 'nav.voip.softswitch.trunk-group-members',
                icon: 'lan',
                route: '/voip/softswitch/trunk-group-members',
              },
            ],
          },
          {
            id: 'voip/softswitch/dialplan',
            label: 'nav.voip.softswitch.dialplan',
            icon: 'route',
            children: [
              {
                id: 'voip/softswitch/routes',
                label: 'nav.voip.softswitch.routes',
                icon: 'alt_route',
                route: '/voip/softswitch/routes',
              },
              {
                id: 'voip/softswitch/dialplans',
                label: 'nav.voip.softswitch.dialplans',
                icon: 'route',
                route: '/voip/softswitch/dialplans',
              },
              {
                id: 'voip/softswitch/dialplan-rules',
                label: 'nav.voip.softswitch.dialplan-rules',
                icon: 'rule',
                route: '/voip/softswitch/dialplan-rules',
              },
            ],
          },
          {
            id: 'voip/softswitch/rates',
            label: 'nav.voip.softswitch.rates',
            icon: 'payments',
            route: '/voip/softswitch/rates',
          },
          {
            id: 'voip/softswitch/cdrs',
            label: 'nav.voip.softswitch.cdrs',
            icon: 'receipt_long',
            route: '/voip/softswitch/cdrs',
          },
        ],
      },
      {
        id: 'voip/pabx',
        label: 'nav.voip.pabx',
        icon: 'phone_in_talk',
        children: [
          {
            id: 'voip/pabx/dashboard',
            label: 'nav.voip.pabx.dashboard',
            icon: 'dashboard',
            route: '/voip/pabx',
            masterRoute: '/system/pabx',
          },
          {
            id: 'voip/pabx/server',
            label: 'nav.voip.pabx.server',
            icon: 'dns',
            route: '/system/pabx/server',
            masterRoute: '/system/pabx/server',
            permissions: ['platform.master.access'],
          },
          {
            id: 'voip/pabx/domains',
            label: 'nav.voip.pabx.domains',
            icon: 'language',
            route: '/voip/pabx/domains',
          },
          {
            id: 'voip/pabx/registry',
            label: 'nav.voip.pabx.registry',
            icon: 'settings_phone',
            route: '/voip/pabx/accounts',
          },
          {
            id: 'voip/pabx/trunks',
            label: 'nav.voip.pabx.trunks',
            icon: 'settings_input_component',
            route: '/voip/pabx/trunks',
          },
          {
            id: 'voip/pabx/extension',
            label: 'nav.voip.pabx.extension',
            icon: 'dialpad',
            route: '/voip/pabx/extension',
          },
          {
            id: 'voip/pabx/inbound-routes',
            label: 'nav.voip.pabx.inbound-routes',
            icon: 'call_received',
            route: '/voip/pabx/inbound-routes',
          },
          {
            id: 'voip/pabx/ivr',
            label: 'nav.voip.pabx.ivr',
            icon: 'account_tree',
            route: '/voip/pabx/ivr',
          },
          {
            id: 'voip/pabx/custom',
            label: 'nav.voip.pabx.custom',
            icon: 'alt_route',
            route: '/voip/pabx/custom',
            entitlementCode: 'module.voip.pabx.custom',
          },
          {
            id: 'voip/pabx/group',
            label: 'nav.voip.pabx.group',
            icon: 'ring_volume',
            route: '/voip/pabx/group',
          },
          {
            id: 'voip/pabx/queue/queues',
            label: 'nav.voip.pabx.queue.queues',
            icon: 'groups',
            route: '/voip/pabx/queue',
          },
          {
            id: 'voip/pabx/queue/agents',
            label: 'nav.voip.pabx.queue.agents',
            icon: 'support_agent',
            route: '/voip/pabx/queue-agents',
          },
          {
            id: 'voip/pabx/cdr',
            label: 'nav.voip.pabx.cdr',
            icon: 'receipt_long',
            route: '/voip/pabx/cdr',
          },
          {
            id: 'voip/pabx/dial-plan',
            label: 'nav.voip.pabx.dial-plan',
            icon: 'rule',
            children: [
              {
                id: 'voip/pabx/dial-plan/plan',
                label: 'nav.voip.pabx.dial-plan.plan',
                icon: 'fact_check',
                route: '/voip/pabx/dial-plan/plan',
              },
              {
                id: 'voip/pabx/dial-plan/rules',
                label: 'nav.voip.pabx.dial-plan.rules',
                icon: 'rule',
                route: '/voip/pabx/dial-plan/rules',
              },
            ],
          },
          {
            id: 'voip/pabx/blacklist',
            label: 'nav.voip.pabx.blacklist',
            icon: 'block',
            children: [
              {
                id: 'voip/pabx/blacklist/list',
                label: 'nav.voip.pabx.blacklist.list',
                icon: 'format_list_bulleted',
                route: '/voip/pabx/blacklist/list',
              },
              {
                id: 'voip/pabx/blacklist/number',
                label: 'nav.voip.pabx.blacklist.number',
                icon: 'pin',
                route: '/voip/pabx/blacklist/number',
              },
            ],
          },
          {
            id: 'voip/pabx/media-files',
            label: 'nav.voip.pabx.media-files',
            icon: 'library_music',
            route: '/voip/pabx/media-files',
          },
        ],
      },
    ],
  },

  // ✅ Realtime media/signaling infrastructure
  {
    id: 'realtime',
    label: 'nav.realtime',
    icon: 'cell_tower',
    entitlementCode: 'module.realtime.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'realtime/dashboard',
        label: 'nav.realtime.dashboard',
        icon: 'dashboard',
        masterRoute: '/system/realtime',
        permissions: ['platform.master.access'],
      },
      {
        id: 'realtime/domain',
        label: 'nav.realtime.domain',
        icon: 'language',
        route: '/realtime/domain',
        masterRoute: '/system/realtime/domain',
      },
      {
        id: 'realtime/webrtc',
        label: 'nav.realtime.webrtc',
        icon: 'settings_input_antenna',
        children: [
          {
            id: 'realtime/webrtc/dashboard',
            label: 'nav.realtime.webrtc.dashboard',
            icon: 'dashboard',
            route: '/realtime/webrtc',
            masterRoute: '/system/realtime/webrtc',
          },
          {
            id: 'realtime/webrtc/domain',
            label: 'nav.realtime.webrtc.domain',
            icon: 'language',
            route: '/realtime/webrtc/domain',
            masterRoute: '/system/realtime/webrtc/domain',
          },
          {
            id: 'realtime/webrtc/server',
            label: 'nav.realtime.webrtc.server',
            icon: 'dns',
            masterRoute: '/system/realtime/webrtc/server',
            permissions: ['platform.master.access'],
          },
          {
            id: 'realtime/webrtc/sip-target',
            label: 'nav.realtime.webrtc.sip-target',
            icon: 'sync_alt',
            route: '/realtime/webrtc/sip-target',
          },
          {
            id: 'realtime/webrtc/parameter',
            label: 'nav.realtime.webrtc.parameter',
            icon: 'tune',
            masterRoute: '/system/realtime/webrtc/parameter',
            permissions: ['platform.master.access'],
          },
        ],
      },
      {
        id: 'realtime/media',
        label: 'nav.realtime.media',
        icon: 'settings_ethernet',
        scope: 'master',
        children: [
          {
            id: 'realtime/media/dashboard',
            label: 'nav.realtime.media.dashboard',
            icon: 'dashboard',
            masterRoute: '/system/realtime/media',
            permissions: ['platform.master.access'],
          },
          {
            id: 'realtime/media/domains',
            label: 'nav.realtime.media.domains',
            icon: 'language',
            masterRoute: '/system/realtime/media/domains',
            permissions: ['platform.master.access'],
          },
          {
            id: 'realtime/media/server',
            label: 'nav.realtime.media.server',
            icon: 'dns',
            masterRoute: '/system/realtime/media/server',
            permissions: ['platform.master.access'],
          },
        ],
      },
      {
        id: 'realtime/turn',
        label: 'nav.realtime.turn',
        icon: 'router',
        scope: 'master',
        children: [
          {
            id: 'realtime/turn/dashboard',
            label: 'nav.realtime.turn.dashboard',
            icon: 'dashboard',
            masterRoute: '/system/realtime/turn',
            permissions: ['platform.master.access'],
          },
          {
            id: 'realtime/turn/domains',
            label: 'nav.realtime.turn.domains',
            icon: 'language',
            masterRoute: '/system/realtime/turn/domains',
            permissions: ['platform.master.access'],
          },
          {
            id: 'realtime/turn/server',
            label: 'nav.realtime.turn.server',
            icon: 'dns',
            masterRoute: '/system/realtime/turn/server',
            permissions: ['platform.master.access'],
          },
        ],
      },
    ],
  },

  // ✅ Hosting (tenant; plataforma usa rotas globais quando disponível)
  {
    id: 'hosting',
    label: 'nav.hosting',
    icon: 'dns',
    entitlementCode: 'module.hosting.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'hosting/dashboard',
        label: 'nav.hosting.dashboard',
        icon: 'dashboard',
        route: '/hosting',
        masterRoute: '/system/hosting',
        requiresEnvironment: true,
      },
      {
        id: 'hosting/dns',
        label: 'nav.hosting.dns',
        icon: 'language',
        entitlementCode: 'module.hosting.dns.zone',
        scope: 'both',
        children: [
          {
            id: 'hosting/dns/dashboard',
            label: 'nav.hosting.dns.dashboard',
            icon: 'dashboard',
            route: '/hosting/dns',
            masterRoute: '/system/hosting/dns',
            scope: 'both',
          },
          {
            id: 'hosting/dns/providers',
            label: 'nav.hosting.dns.providers',
            icon: 'manage_accounts',
            route: '/hosting/dns/providers',
            masterRoute: '/system/hosting/dns/providers',
            scope: 'both',
          },
          {
            id: 'hosting/dns/registers',
            label: 'nav.hosting.dns.registers',
            icon: 'app_registration',
            route: '/hosting/dns/registers',
            masterRoute: '/system/hosting/dns/registers',
            scope: 'both',
          },
          {
            id: 'hosting/dns/domains',
            label: 'nav.hosting.dns.domains',
            icon: 'language',
            route: '/hosting/dns/domains',
            masterRoute: '/system/hosting/dns/domains',
            scope: 'both',
          },
        ],
      },
      {
        id: 'hosting/smtp',
        label: 'nav.hosting.smtp',
        icon: 'mark_email_read',
        children: [
          {
            id: 'hosting/smtp/dashboard',
            label: 'nav.hosting.smtp.dashboard',
            icon: 'dashboard',
            route: '/hosting/smtp',
            masterRoute: '/system/hosting/smtp',
          },
          {
            id: 'hosting/smtp/providers',
            label: 'nav.hosting.smtp.providers',
            icon: 'cloud_sync',
            route: '/hosting/smtp/providers',
            masterRoute: '/system/hosting/smtp/providers',
          },
          {
            id: 'hosting/smtp/accounts',
            label: 'nav.hosting.smtp.accounts',
            icon: 'alternate_email',
            route: '/hosting/smtp/accounts',
            masterRoute: '/system/hosting/smtp/accounts',
          },
          {
            id: 'hosting/smtp/routes',
            label: 'nav.hosting.smtp.routes',
            icon: 'route',
            route: '/hosting/smtp/routes',
            masterRoute: '/system/hosting/smtp/routes',
          },
        ],
      },
      {
        id: 'hosting/storage',
        label: 'nav.hosting.storage',
        icon: 'storage',
        entitlementCode: 'module.hosting.storage.account',
        children: [
          {
            id: 'hosting/storage/dashboard',
            label: 'nav.hosting.storage.dashboard',
            icon: 'dashboard',
            route: '/hosting/storage',
            masterRoute: '/system/hosting/storage',
          },
          {
            id: 'hosting/storage/providers',
            label: 'nav.hosting.storage.providers',
            icon: 'cloud_sync',
            masterRoute: '/system/hosting/storage/providers',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/storage/accounts',
            label: 'nav.hosting.storage.accounts',
            icon: 'inventory_2',
            route: '/hosting/storage/accounts',
            masterRoute: '/system/hosting/storage/accounts',
          },
        ],
      },
      {
        id: 'hosting/vps',
        label: 'nav.hosting.vps',
        icon: 'cloud',
        children: [
          {
            id: 'hosting/vps/dashboard',
            label: 'nav.hosting.vps.dashboard',
            icon: 'dashboard',
            route: '/hosting/vps',
            masterRoute: '/system/vps',
          },
          {
            id: 'hosting/vps/provider',
            label: 'nav.hosting.vps.provider',
            icon: 'cloud_sync',
            masterRoute: '/system/vps/provider',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/vps/plans',
            label: 'nav.hosting.vps.plans',
            icon: 'view_list',
            masterRoute: '/system/vps/plans',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/vps/instances',
            label: 'nav.hosting.vps.instances',
            icon: 'dns',
            route: '/hosting/vps/instances',
            masterRoute: '/system/vps/instances',
          },
          {
            id: 'hosting/vps/snapshots',
            label: 'nav.hosting.vps.snapshots',
            icon: 'photo_camera',
            route: '/hosting/vps/snapshots',
            masterRoute: '/system/vps/snapshots',
            entitlementCode: 'module.hosting.vps.snapshot',
          },
          {
            id: 'hosting/vps/networks',
            label: 'nav.hosting.vps.networks',
            icon: 'lan',
            route: '/hosting/vps/networks',
            masterRoute: '/system/vps/networks',
            entitlementCode: 'module.hosting.vps.network',
          },
          {
            id: 'hosting/vps/firewalls',
            label: 'nav.hosting.vps.firewalls',
            icon: 'security',
            route: '/hosting/vps/firewalls',
            masterRoute: '/system/vps/firewalls',
            entitlementCode: 'module.hosting.vps.firewall',
          },
        ],
      },
      {
        id: 'hosting/vps-container',
        label: 'nav.hosting.vps-container',
        icon: 'apps',
        children: [
          {
            id: 'hosting/vps-container/dashboard',
            label: 'nav.hosting.vps-container.dashboard',
            icon: 'dashboard',
            route: '/hosting/vps-container',
            masterRoute: '/system/vps-container',
          },
          {
            id: 'hosting/vps-container/provider',
            label: 'nav.hosting.vps-container.provider',
            icon: 'cloud_sync',
            masterRoute: '/system/vps-container/provider',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/vps-container/plans',
            label: 'nav.hosting.vps-container.plans',
            icon: 'view_list',
            masterRoute: '/system/vps-container/plans',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/vps-container/instances',
            label: 'nav.hosting.vps-container.instances',
            icon: 'dns',
            route: '/hosting/vps-container/instances',
            masterRoute: '/system/vps-container/instances',
            entitlementCode: 'module.hosting.vps-container.instance',
          },
        ],
      },
      {
        id: 'hosting/webhost',
        label: 'nav.hosting.webhost',
        icon: 'web',
        children: [
          {
            id: 'hosting/webhost/dashboard',
            label: 'nav.hosting.webhost.dashboard',
            icon: 'dashboard',
            route: '/hosting/webhost',
            masterRoute: '/system/hosting/webhost',
          },
          {
            id: 'hosting/webhost/providers',
            label: 'nav.hosting.webhost.providers',
            icon: 'admin_panel_settings',
            masterRoute: '/system/hosting/webhost/providers',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/webhost/plans',
            label: 'nav.hosting.webhost.plans',
            icon: 'view_list',
            masterRoute: '/system/hosting/webhost/plans',
            scope: 'master',
            permissions: ['platform.master.access'],
          },
          {
            id: 'hosting/webhost/hosts',
            label: 'nav.hosting.webhost.hosts',
            icon: 'dns',
            route: '/hosting/webhost/hosts',
            scope: 'tenant',
            entitlementCode: 'module.hosting.webhost.plan',
          },
          {
            id: 'hosting/webhost/emails',
            label: 'nav.hosting.webhost.emails',
            icon: 'alternate_email',
            route: '/hosting/webhost/emails',
            scope: 'tenant',
            entitlementCode: 'module.hosting.webhost.plan',
          },
          {
            id: 'hosting/webhost/database',
            label: 'nav.hosting.webhost.database',
            icon: 'storage',
            entitlementCode: 'module.hosting.webhost.plan',
            children: [
              {
                id: 'hosting/webhost/databases',
                label: 'nav.hosting.webhost.databases',
                icon: 'storage',
                route: '/hosting/webhost/databases',
                scope: 'tenant',
                entitlementCode: 'module.hosting.webhost.plan',
              },
              {
                id: 'hosting/webhost/database-users',
                label: 'nav.hosting.webhost.database-users',
                icon: 'person',
                route: '/hosting/webhost/database-users',
                scope: 'tenant',
                entitlementCode: 'module.hosting.webhost.plan',
              },
              {
                id: 'hosting/webhost/database-grants',
                label: 'nav.hosting.webhost.database-grants',
                icon: 'key',
                route: '/hosting/webhost/database-grants',
                scope: 'tenant',
                entitlementCode: 'module.hosting.webhost.plan',
              },
            ],
          },
          {
            id: 'hosting/webhost/mailing-lists',
            label: 'nav.hosting.webhost.mailing-lists',
            icon: 'forward_to_inbox',
            route: '/hosting/webhost/mailing-lists',
            scope: 'tenant',
            entitlementCode: 'module.hosting.webhost.plan',
          },
          {
            id: 'hosting/webhost/zone-editor',
            label: 'nav.hosting.webhost.zone-editor',
            icon: 'edit_location_alt',
            route: '/hosting/webhost/zone-editor',
            scope: 'tenant',
            entitlementCode: 'module.hosting.webhost.plan',
          },
        ],
      },
    ],
  },

  // ✅ Support (tenant) — visible only when an environment is selected
  {
    id: 'support',
    label: 'nav.support',
    icon: 'support_agent',
    entitlementCode: 'module.support.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'support/tickets',
        label: 'nav.support.tickets',
        icon: 'confirmation_number',
        children: [
          {
            id: 'support/tickets/registry',
            label: 'nav.support.tickets.registry',
            icon: 'badge',
            route: '/support/tickets',
          },
          {
            id: 'support/tickets/types',
            label: 'nav.support.tickets.types',
            icon: 'category',
            route: '/support/ticket-types',
          },
          {
            id: 'support/tickets/priorities',
            label: 'nav.support.tickets.priorities',
            icon: 'low_priority',
            route: '/support/ticket-priorities',
          },
          {
            id: 'support/tickets/channels',
            label: 'nav.support.tickets.channels',
            icon: 'call_split',
            route: '/support/ticket-channels',
          },
          {
            id: 'support/tickets/teams',
            label: 'nav.support.tickets.teams',
            icon: 'groups',
            route: '/support/teams',
          },
        ],
      },
      {
        id: 'support/channels',
        label: 'nav.support.channels',
        icon: 'hub',
        route: '/support/channels',
      },
      {
        id: 'support/attendance',
        label: 'nav.support.attendance',
        icon: 'forum',
        route: '/support/attendance',
      },
    ],
  },

  // Platform support desk: the MNSCloud team answers tenants (platform.support.* permissions).
  {
    id: 'support-desk',
    label: 'nav.support-desk',
    icon: 'headset_mic',
    scope: 'public',
    children: [
      {
        id: 'support-desk/tickets',
        label: 'nav.support-desk.tickets',
        icon: 'confirmation_number',
        route: '/support-desk/tickets',
        scope: 'public',
        permissions: ['platform.support.tickets.manage'],
      },
      {
        id: 'support-desk/teams',
        label: 'nav.support-desk.teams',
        icon: 'groups',
        route: '/support-desk/teams',
        scope: 'public',
        permissions: ['platform.support.settings.manage'],
      },
      {
        id: 'support-desk/ticket-types',
        label: 'nav.support-desk.ticket-types',
        icon: 'category',
        route: '/support-desk/ticket-types',
        scope: 'public',
        permissions: ['platform.support.settings.manage'],
      },
      {
        id: 'support-desk/ticket-priorities',
        label: 'nav.support-desk.ticket-priorities',
        icon: 'low_priority',
        route: '/support-desk/ticket-priorities',
        scope: 'public',
        permissions: ['platform.support.settings.manage'],
      },
      {
        id: 'support-desk/ticket-origins',
        label: 'nav.support-desk.ticket-origins',
        icon: 'call_split',
        route: '/support-desk/ticket-origins',
        scope: 'public',
        permissions: ['platform.support.settings.manage'],
      },
    ],
  },

  {
    id: 'monitoring',
    label: 'nav.monitoring',
    icon: 'monitor_heart',
    entitlementCode: 'module.monitoring.*',
    children: [
      {
        id: 'monitoring/dashboard',
        label: 'nav.monitoring.dashboard',
        icon: 'dashboard',
        route: '/monitoring',
        masterRoute: '/system/monitoring',
        permissions: ['tenant.monitoring.activity.read'],
        requiresEnvironment: true,
      },
      {
        id: 'monitoring/overview',
        label: 'nav.monitoring.overview',
        icon: 'show_chart',
        route: '/monitoring/overview',
        masterRoute: '/system/monitoring/overview',
        permissions: ['tenant.monitoring.agents.read'],
        requiresEnvironment: true,
      },
      {
        id: 'monitoring/agents',
        label: 'nav.monitoring.agents',
        icon: 'sensors',
        route: '/monitoring/agents',
        masterRoute: '/system/monitoring/agents',
        permissions: ['tenant.monitoring.agents.read'],
        requiresEnvironment: true,
      },
      {
        id: 'monitoring/activity-logs',
        label: 'nav.monitoring.activity-logs',
        icon: 'fact_check',
        route: '/monitoring/activity-logs',
        masterRoute: '/system/monitoring/activity-logs',
        permissions: ['tenant.monitoring.activity.read'],
        requiresEnvironment: true,
      },
      {
        id: 'monitoring/notification-rules',
        label: 'nav.monitoring.notification-rules',
        icon: 'notifications_active',
        masterRoute: '/system/monitoring/notification-rules',
        scope: 'master',
        permissions: ['tenant.monitoring.activity.read'],
        requiresEnvironment: false,
      },
      {
        id: 'monitoring/runtime-reconcile',
        label: 'nav.monitoring.runtime-reconcile',
        icon: 'tune',
        masterRoute: '/system/monitoring/runtime-reconcile',
        scope: 'master',
        requiresEnvironment: false,
      },
    ],
  },
  {
    id: 'cyber-security',
    label: 'nav.cyber-security',
    icon: 'security',
    entitlementCode: 'module.cyber-security.*',
    permissions: ['tenant.access.manage'],
    requiresEnvironment: true,
    masterRoute: '/system/cyber-security',
    children: [
      {
        id: 'cyber-security/dashboard',
        label: 'nav.cyber-security.dashboard',
        icon: 'dashboard',
        route: '/cyber-security',
        masterRoute: '/system/cyber-security',
        permissions: ['tenant.access.manage'],
        requiresEnvironment: true,
      },
      {
        id: 'cyber-security/protection',
        label: 'nav.cyber-security.protection',
        icon: 'shield',
        children: [
          {
            id: 'cyber-security/servers',
            label: 'nav.cyber-security.servers',
            icon: 'dns',
            route: '/cyber-security/servers',
            masterRoute: '/system/cyber-security/servers',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/profiles',
            label: 'nav.cyber-security.profiles',
            icon: 'shield',
            route: '/cyber-security/profiles',
            masterRoute: '/system/cyber-security/profiles',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/services',
            label: 'nav.cyber-security.services',
            icon: 'settings_applications',
            route: '/cyber-security/services',
            masterRoute: '/system/cyber-security/services',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/lists',
            label: 'nav.cyber-security.lists',
            icon: 'rule',
            route: '/cyber-security/lists',
            masterRoute: '/system/cyber-security/lists',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
        ],
      },
      {
        id: 'cyber-security/threats-events',
        label: 'nav.cyber-security.threats-events',
        icon: 'notification_important',
        children: [
          {
            id: 'cyber-security/alerts',
            label: 'nav.cyber-security.alerts',
            icon: 'notification_important',
            route: '/cyber-security/alerts',
            masterRoute: '/system/cyber-security/alerts',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/decisions',
            label: 'nav.cyber-security.decisions',
            icon: 'gavel',
            route: '/cyber-security/decisions',
            masterRoute: '/system/cyber-security/decisions',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/security-events',
            label: 'nav.cyber-security.security-events',
            icon: 'manage_search',
            route: '/cyber-security/security-events',
            masterRoute: '/system/cyber-security/security-events',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
        ],
      },
      {
        id: 'cyber-security/access-control',
        label: 'nav.cyber-security.access-control',
        icon: 'policy',
        children: [
          {
            id: 'cyber-security/trusted-nodes',
            label: 'nav.cyber-security.trusted-nodes',
            icon: 'hub',
            route: '/cyber-security/trusted-nodes',
            masterRoute: '/system/cyber-security/trusted-nodes',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/network-policies',
            label: 'nav.cyber-security.network-policies',
            icon: 'policy',
            route: '/cyber-security/network-policies',
            masterRoute: '/system/cyber-security/network-policies',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
        ],
      },
      {
        id: 'cyber-security/secrets-manager',
        label: 'nav.cyber-security.secrets-manager',
        icon: 'key',
        entitlementCode: 'module.cyber-security.secrets',
        permissions: ['tenant.access.manage'],
        requiresEnvironment: true,
        children: [
          {
            id: 'cyber-security/secrets/dashboard',
            label: 'nav.cyber-security.secrets.dashboard',
            icon: 'dashboard',
            route: '/cyber-security/secrets/dashboard',
            masterRoute: '/system/cyber-security/secrets/dashboard',
            entitlementCode: 'module.cyber-security.secrets',
            permissions: ['tenant.cyber-security.secrets.read'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/secrets',
            label: 'nav.cyber-security.secrets',
            icon: 'key',
            route: '/cyber-security/secrets',
            masterRoute: '/system/cyber-security/secrets',
            entitlementCode: 'module.cyber-security.secrets',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/secret-accounts',
            label: 'nav.cyber-security.secret-accounts',
            icon: 'manage_accounts',
            route: '/cyber-security/secret-accounts',
            masterRoute: '/system/cyber-security/secret-accounts',
            entitlementCode: 'module.cyber-security.secret-accounts',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: true,
          },
          {
            id: 'cyber-security/secret-servers',
            label: 'nav.cyber-security.secret-servers',
            icon: 'admin_panel_settings',
            masterRoute: '/system/cyber-security/secret-servers',
            scope: 'master',
            permissions: ['tenant.access.manage'],
            requiresEnvironment: false,
          },
        ],
      },
    ],
  },

  // ✅ Sale (tenant) — requer ambiente selecionado
  {
    id: 'sale',
    label: 'nav.sale',
    icon: 'point_of_sale',
    entitlementCode: 'module.sale.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'sale/stock',
        label: 'nav.sale.stock',
        icon: 'inventory_2',
        children: [
          {
            id: 'sale/stock/registry',
            label: 'nav.sale.stock.registry',
            icon: 'badge',
            route: '/sale/stock',
          },
          {
            id: 'sale/stock/type',
            label: 'nav.sale.stock.type',
            icon: 'category',
            route: '/sale/stock-type',
          },
        ],
      },
      { id: 'sale/unit', label: 'nav.sale.unit', icon: 'straighten', route: '/sale/unit' },
      {
        id: 'sale/brand',
        label: 'nav.sale.brand',
        icon: 'branding_watermark',
        route: '/sale/brand',
      },
      { id: 'sale/category', label: 'nav.sale.category', icon: 'sell', route: '/sale/category' },
      {
        id: 'sale/product',
        label: 'nav.sale.product',
        icon: 'shopping_bag',
        route: '/sale/product',
      },
      {
        id: 'sale/quotation',
        label: 'nav.sale.quotation',
        icon: 'request_quote',
        route: '/sale/quotation',
      },
    ],
  },

  // ✅ Clinic (tenant) — requer ambiente selecionado
  {
    id: 'clinic',
    label: 'nav.clinic',
    icon: 'local_hospital',
    entitlementCode: 'module.clinic.*',
    requiresEnvironment: true,
    children: [
      {
        id: 'clinic/catalog',
        label: 'nav.clinic.catalog',
        icon: 'inventory_2',
        children: [
          {
            id: 'clinic/agreements',
            label: 'nav.clinic.agreements',
            icon: 'health_and_safety',
            route: '/clinic/agreements',
          },
          {
            id: 'clinic/agreement-plans',
            label: 'nav.clinic.agreement-plans',
            icon: 'card_membership',
            route: '/clinic/agreement-plans',
          },
          {
            id: 'clinic/procedures',
            label: 'nav.clinic.procedures',
            icon: 'biotech',
            route: '/clinic/procedures',
          },
          {
            id: 'clinic/coverages',
            label: 'nav.clinic.coverages',
            icon: 'fact_check',
            route: '/clinic/coverages',
          },
        ],
      },
      {
        id: 'clinic/operations',
        label: 'nav.clinic.operations',
        icon: 'settings_suggest',
        children: [
          {
            id: 'clinic/customer-agreements',
            label: 'nav.clinic.customer-agreements',
            icon: 'group',
            route: '/clinic/customer-agreements',
          },
          {
            id: 'clinic/bradesco-siad/guides',
            label: 'nav.clinic.bradesco-siad.guides',
            icon: 'description',
            route: '/clinic/bradesco/siad/guides',
          },
        ],
      },
    ],
  },

  // ✅ Laboratory (tenant) — requer ambiente selecionado
  {
    id: 'laboratory',
    label: 'nav.laboratory',
    icon: 'biotech',
    entitlementCode: 'module.laboratory.*',
    requiresEnvironment: true,
  },

  // Settings (raiz) — última posição
  {
    id: 'settings',
    label: 'nav.settings',
    icon: 'settings',
    children: [
      { id: 'settings/general', label: 'nav.settings.general', icon: 'tune', route: '/settings' },
      {
        id: 'settings/themes',
        label: 'nav.settings.themes',
        icon: 'palette',
        route: '/settings/themes',
      },

      // Tenant access management.
      {
        id: 'settings/tenants',
        label: 'nav.settings.tenants',
        icon: 'apartment',
        route: '/settings/tenants',
        permissions: ['tenant.access.manage'],
        requiresEnvironment: true,
      },
      {
        id: 'settings/parameters',
        label: 'nav.settings.parameters',
        icon: 'tune',
        route: '/settings/parameters',
        masterRoute: '/system/parameters',
        permissions: ['tenant.access.manage'],
        requiresEnvironment: true,
      },
    ],
  },
];
