import { Component } from '@angular/core';

import {
  ConfigurableCrudConfig,
  ConfigurableCrudPageBase,
  ConfigurableCrudRecord,
  CONFIGURABLE_CRUD_IMPORTS,
} from '../../../shared/crud/configurable-crud/configurable-crud-page-base';

const COMPANY_CONFIG: ConfigurableCrudConfig = {
  endpoint: 'erp/companies',
  uuidField: 'CompanyUUID',
  pageTitle: 'Companies',
  pageDescription: 'Manage official companies and fiscal registration data.',
  createTitle: 'New company',
  editTitle: 'Edit company',
  dialogDescription: 'Maintain company registration, contact and address data.',
  searchPlaceholder: 'Search',
  emptyLabel: 'No companies found.',
  deleteTitle: 'Delete company',
  deleteMessage: 'Are you sure you want to delete this company?',
  deleteSelectedTitle: 'Delete selected companies',
  deleteSelectedMessage: 'Delete {count} selected companies?',
  savedMessage: 'Company saved successfully.',
  deletedMessage: 'Company deleted successfully.',
  deleteFailedMessage: 'Failed to delete company.',
  statusMode: 'string',
  activeValue: 'active',
  inactiveValue: 'inactive',
  initialValues: {
    status: 'active',
    name: '',
    legalName: '',
    document: '',
    email: '',
    phone: '',
    addressStreet: '',
    addressNumber: '',
    addressDistrict: '',
    addressCity: '',
    addressState: '',
    addressZip: '',
    addressCountry: '',
    addressComplement: '',
    notes: '',
  },
  columns: [
    { id: 'name', label: 'Name', kind: 'identity', field: 'Name', uuidField: 'CompanyUUID' },
    { id: 'document', label: 'Document', field: 'Document', className: 'document-col' },
    { id: 'email', label: 'E-mail', field: 'Email', className: 'email-col' },
    { id: 'phone', label: 'Phone', field: 'Phone', className: 'phone-col' },
    { id: 'status', label: 'Status', kind: 'status', field: 'Status', className: 'status-col' },
  ],
  fields: [
    {
      key: 'status',
      source: 'Status',
      payloadKey: 'status',
      label: 'Status',
      type: 'status',
      span: 1,
    },
    { key: 'document', source: 'Document', payloadKey: 'document', label: 'Document', span: 1 },
    {
      key: 'name',
      source: 'Name',
      payloadKey: 'name',
      label: 'Name',
      required: true,
      span: 2,
      breakBefore: true,
    },
    {
      key: 'legalName',
      source: 'LegalName',
      payloadKey: 'legalName',
      label: 'Legal name',
      span: 2,
    },
    {
      key: 'email',
      source: 'Email',
      payloadKey: 'email',
      label: 'E-mail',
      type: 'email',
      span: 1,
      breakBefore: true,
    },
    { key: 'phone', source: 'Phone', payloadKey: 'phone', label: 'Phone', type: 'phone', span: 1 },
    {
      key: 'addressZip',
      source: 'AddressZip',
      payloadKey: 'addressZip',
      label: 'Zip',
      tab: 'address',
      span: 1,
      postalLookup: {
        streetKey: 'addressStreet',
        districtKey: 'addressDistrict',
        complementKey: 'addressComplement',
        cityKey: 'addressCity',
        stateKey: 'addressState',
        countryKey: 'addressCountry',
        numberKey: 'addressNumber',
      },
    },
    {
      key: 'addressStreet',
      source: 'AddressStreet',
      payloadKey: 'addressStreet',
      label: 'Street',
      tab: 'address',
      span: 1,
    },
    {
      key: 'addressNumber',
      source: 'AddressNumber',
      payloadKey: 'addressNumber',
      label: 'Number',
      tab: 'address',
      span: 1,
    },
    {
      key: 'addressDistrict',
      source: 'AddressDistrict',
      payloadKey: 'addressDistrict',
      label: 'District',
      tab: 'address',
      span: 1,
    },
    {
      key: 'addressComplement',
      source: 'AddressComplement',
      payloadKey: 'addressComplement',
      label: 'Complement',
      tab: 'address',
      span: 1,
    },
    {
      key: 'addressCity',
      source: 'AddressCity',
      payloadKey: 'addressCity',
      label: 'City',
      tab: 'address',
      span: 1,
    },
    {
      key: 'addressState',
      source: 'AddressState',
      payloadKey: 'addressState',
      label: 'State',
      tab: 'address',
      span: 1,
    },
    {
      key: 'addressCountry',
      source: 'AddressCountry',
      payloadKey: 'addressCountry',
      label: 'Country',
      tab: 'address',
      span: 1,
    },
    {
      key: 'notes',
      source: 'Notes',
      payloadKey: 'notes',
      label: 'Note',
      type: 'textarea',
      tab: 'notes',
      span: 4,
      rows: 4,
    },
  ],
};

@Component({
  selector: 'app-erp-companies',
  standalone: true,
  imports: CONFIGURABLE_CRUD_IMPORTS,
  templateUrl: '../../../shared/crud/configurable-crud/configurable-crud-page.html',
  styleUrls: ['../../../shared/crud/configurable-crud/configurable-crud-page.scss'],
})
export class ErpCompaniesPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> {
  constructor() {
    super(COMPANY_CONFIG);
  }
}
