import { CRM_OPTIONS } from '../crm-options';
import { crmPayload, crmLocalDate, crmLocalTime } from '../crm-input';
import { Component } from '@angular/core';
import {
  CONFIGURABLE_CRUD_IMPORTS,
  ConfigurableCrudPageBase,
  ConfigurableCrudRecord,
} from '../../../shared/crud/configurable-crud/configurable-crud-page-base';
import { defineCrud } from '../../../shared/crud/configurable-crud/define-crud';
import { crmActions } from '../crm-actions';
const config = defineCrud({
  endpoint: 'crm/activities',
  uuidField: 'CatUUID',
  pageTitle: 'crm.title.activities',
  initialValues: {
    CatName: '',
    CrmLeadCleUUID: '',
    CrmOpportunityCopUUID: '',
    CatKind: 'task',
    CatDueAt: '',
    CatState: 'planned',
    notes: '',
    CatStatus: 1,
    AssignedUserUsrUUID: '',
  },
  fields: [
    {
      key: 'CatStatus',
      source: 'CatStatus',
      label: 'crm.field.Status',
      span: 1,
      required: true,
      type: 'status',
    },
    {
      key: 'CatKind',
      source: 'CatKind',
      label: 'crm.field.Kind',
      span: 1,
      required: true,
      type: 'select',
      translateOptions: true,
      options: CRM_OPTIONS.activityKinds,
    },
    {
      key: 'CatState',
      source: 'CatState',
      label: 'crm.field.State',
      span: 1,
      required: true,
      type: 'select',
      translateOptions: true,
      options: CRM_OPTIONS.activityStates,
    },
    {
      key: 'AssignedUserUsrUUID',
      source: 'AssignedUserUsrUUID',
      label: 'crm.field.AssignedUserUsrUUID',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        endpoint: 'crm/members',
        uuidField: 'UsrUUID',
        labelField: 'UsrName',
      },
      quickCreate: false,
      quickCreateExemptReason:
        'Assignment selects existing tenant members; membership is managed through the canonical tenant invitation flow.',
    },
    {
      key: 'CatName',
      source: 'CatName',
      label: 'crm.field.Name',
      span: 2,
      required: true,
      type: 'text',
    },
    {
      key: 'CrmLeadCleUUID',
      source: 'CrmLeadCleUUID',
      label: 'crm.title.leads',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        endpoint: 'crm/leads',
        uuidField: 'CleUUID',
        labelField: 'CleName',
        selectedLabelField: 'CrmLeadCleUUIDName',
      },
    },
    {
      key: 'CrmOpportunityCopUUID',
      source: 'CrmOpportunityCopUUID',
      label: 'crm.title.opportunities',
      span: 1,
      required: false,
      type: 'search-select',
      remoteLookup: {
        selectedLabelField: 'CrmOpportunityCopUUIDName',
        endpoint: 'crm/opportunities',
        uuidField: 'CopUUID',
        labelField: 'CopName',
      },
    },
    {
      key: 'CatDueAt',
      source: 'CatDueAt',
      label: 'crm.field.DueAt',
      span: 1,
      required: true,
      type: 'date',
      fromRecord: crmLocalDate,
      breakBefore: true,
    },
    {
      key: 'CatDueAtTime',
      source: 'CatDueAt',
      label: 'Time',
      type: 'time',
      span: 1,
      fromRecord: crmLocalTime,
      requiredWhen: ({ values }) => Boolean(values['CatDueAt']),
    },
    {
      key: 'notes',
      source: 'CatNotes',
      label: 'Notes',
      span: 4,
      required: false,
      type: 'textarea',
      payloadKey: 'CatNotes',
      tab: 'notes',
      rows: 4,
    },
    { key: 'CatRevision', source: 'CatRevision', label: 'crm.field.Revision', hidden: true },
  ],
  columns: [
    { id: 'CrmLeadCleUUID', field: 'CrmLeadCleUUIDName', label: 'crm.title.leads', kind: 'text' },
    {
      id: 'CrmOpportunityCopUUID',
      field: 'CrmOpportunityCopUUIDName',
      label: 'crm.title.opportunities',
      kind: 'text',
    },
    {
      id: 'CatName',
      field: 'CatName',
      label: 'crm.field.Name',
      kind: 'identity',
    },
    {
      id: 'CatKind',
      field: 'CatKind',
      label: 'crm.field.Kind',
      kind: 'text',
      options: CRM_OPTIONS.activityKinds,
    },
    {
      id: 'CatDueAt',
      field: 'CatDueAt',
      label: 'crm.field.DueAt',
      kind: 'datetime',
    },
    {
      id: 'CatState',
      field: 'CatState',
      label: 'crm.field.State',
      kind: 'text',
      options: CRM_OPTIONS.activityStates,
    },
    {
      id: 'CatStatus',
      field: 'CatStatus',
      label: 'crm.field.Status',
      kind: 'status',
    },
  ],
  listFilters: [
    {
      key: 'CrmLeadCleUUID',
      paramKey: 'CrmLeadCleUUID',
      label: 'crm.title.leads',
      type: 'search-select',
      span: 1,
      remoteLookup: { endpoint: 'crm/leads', uuidField: 'CleUUID', labelField: 'CleName' },
    },
    {
      key: 'CrmOpportunityCopUUID',
      paramKey: 'CrmOpportunityCopUUID',
      label: 'crm.title.opportunities',
      type: 'search-select',
      span: 1,
      remoteLookup: {
        selectedLabelField: 'CrmOpportunityCopUUIDName',
        endpoint: 'crm/opportunities',
        uuidField: 'CopUUID',
        labelField: 'CopName',
      },
    },
    {
      key: 'AssignedUserUsrUUID',
      paramKey: 'AssignedUserUsrUUID',
      label: 'crm.field.AssignedUserUsrUUID',
      type: 'search-select',
      span: 1,
      remoteLookup: { endpoint: 'crm/members', uuidField: 'UsrUUID', labelField: 'UsrName' },
    },
    {
      key: 'CatKind',
      paramKey: 'CatKind',
      label: 'crm.field.Kind',
      type: 'select',
      translateOptions: true,
      options: CRM_OPTIONS.activityKinds,
      span: 1,
    },
    {
      key: 'CatState',
      paramKey: 'CatState',
      label: 'crm.field.State',
      type: 'select',
      translateOptions: true,
      options: CRM_OPTIONS.activityStates,
      span: 1,
    },
  ],
  serverSidePagination: true,
  // CRM deletion is individually audited; see app.md, CRM form baseline.
  bulkDelete: false,
  quickCreateLabelField: 'CatName',
  payload: (values, editing) =>
    crmPayload(values, editing, 'CatRevision', ['CatStatus', 'CatRevision'], ['CatDueAt']),
  rowActions: crmActions('activities'),
});
@Component({
  selector: 'app-crm-activities',
  standalone: true,
  imports: CONFIGURABLE_CRUD_IMPORTS,
  templateUrl: '../../../shared/crud/configurable-crud/configurable-crud-page.html',
  styleUrls: ['../../../shared/crud/configurable-crud/configurable-crud-page.scss'],
})
export class CrmActivityPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> {
  constructor() {
    super(config);
  }
}
