export type VoipSoftswitchSubscriberItem = {
  VsuUUID: string;
  VsuID: string;
  VoipSoftswitchAccountVssUUID: string;
  CustomerCusUUID: string;
  VoipDomainVdmUUID: string;
  VsuUsername: string;
  VsuUsernameType?: 'PUBLIC_E164' | 'INTERNAL' | null;
  VsuPassword: string;
  VsuCallerIdName?: string | null;
  VsuCallerIdNumber?: string | null;
  VsuContext?: string | null;
  VsuRegisterEnabled: number;
  VsuMaxContacts: number;
  VsuMaxConcurrentCalls: number;
  VsuRecordCalls: number;
  VsuOutboundCid?: string | null;
  VsuCodecs?: string | null;
  VsuEnabled: number;
  SoftswitchName?: string | null;
  CustomerName?: string | null;
  DomainName?: string | null;
};
