import { Component } from '@angular/core';
import {
  CONFIGURABLE_CRUD_IMPORTS,
  ConfigurableCrudPageBase,
  ConfigurableCrudRecord,
} from '../../../../../shared/crud/configurable-crud/configurable-crud-page-base';
import { defineCrud } from '../../../../../shared/crud/configurable-crud/define-crud';
import { quickCreateFor } from '../../../../../shared/crud/configurable-crud/quick-create';

const statuses = [
  { value: 'draft', label: 'Draft' },
  { value: 'active', label: 'Active' },
  { value: 'expired', label: 'Expired' },
  { value: 'canceled', label: 'Canceled' },
];

const config = defineCrud({
  endpoint: 'erp/financial/invoicing/contracts',
  uuidField: 'ErpFinInvContractUUID',
  pageTitle: 'Contracts',
  pageDescription: 'Manage contract lifecycle and billing context.',
  searchPlaceholder: 'Search contracts',
  bulkDelete: true,
  statusMode: 'string',
  activeValue: 'active',
  inactiveValue: 'canceled',
  statusOptions: statuses,
  activeStatusValues: ['active'],
  initialValues: {
    status: 'draft',
    title: '',
    customerUUID: '',
    startDate: null,
    endDate: null,
    amount: 0,
    billingComplexUUID: '',
    notes: '',
    addressBillingZip: '',
    addressBillingStreet: '',
    addressBillingNumber: '',
    addressBillingDistrict: '',
    addressBillingCity: '',
    addressBillingState: '',
    addressBillingCountry: '',
    addressInstallZip: '',
    addressInstallStreet: '',
    addressInstallNumber: '',
    addressInstallDistrict: '',
    addressInstallCity: '',
    addressInstallState: '',
    addressInstallCountry: '',
  },
  columns: [
    {
      id: 'title',
      label: 'Title',
      field: 'Title',
      uuidField: 'ErpFinInvContractUUID',
      kind: 'identity',
    },
    { id: 'customer', label: 'Customer', field: 'CustomerName' },
    { id: 'startDate', label: 'Start date', field: 'StartDate', kind: 'date' },
    { id: 'endDate', label: 'End date', field: 'EndDate', kind: 'date' },
    { id: 'amount', label: 'Amount', field: 'Amount', kind: 'currency' },
    { id: 'status', label: 'Status', field: 'Status', kind: 'status' },
  ],
  fields: [
    {
      key: 'status',
      source: 'Status',
      label: 'Status',
      type: 'status',
      options: statuses,
      span: 1,
    },
    { key: 'title', source: 'Title', label: 'Title', required: true, span: 1 },
    {
      key: 'customerUUID',
      source: 'CustomerUUID',
      label: 'Customer',
      type: 'search-select',
      remoteLookup: {
        endpoint: 'erp/customers',
        searchParam: 'q',
        uuidField: 'CustomerUUID',
        labelField: 'Name',
        selectedLabelField: 'CustomerName',
      },
      quickCreate: quickCreateFor('CustomerCusUUID'),
      span: 1,
    },
    { key: 'amount', source: 'Amount', label: 'Amount', type: 'currency', required: true, span: 1 },
    {
      key: 'startDate',
      source: 'StartDate',
      label: 'Start date',
      type: 'date',
      required: true,
      span: 1,
    },
    { key: 'endDate', source: 'EndDate', label: 'End date', type: 'date', span: 1 },
    {
      key: 'billingComplexUUID',
      source: 'BillingComplexUUID',
      label: 'Billing complex',
      type: 'search-select',
      remoteLookup: { endpoint: 'erp/complexes', uuidField: 'ComplexUUID', labelField: 'Name' },
      quickCreate: quickCreateFor('ErpComplexEcxUUID'),
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressBillingZip',
      source: 'AddressBillingZip',
      label: 'Zip',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
      postalLookup: {
        streetKey: 'addressBillingStreet',
        districtKey: 'addressBillingDistrict',
        cityKey: 'addressBillingCity',
        stateKey: 'addressBillingState',
        countryKey: 'addressBillingCountry',
        numberKey: 'addressBillingNumber',
      },
    },
    {
      key: 'addressBillingStreet',
      source: 'AddressBillingStreet',
      label: 'Street',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressBillingNumber',
      source: 'AddressBillingNumber',
      label: 'Number',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressBillingDistrict',
      source: 'AddressBillingDistrict',
      label: 'District',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressBillingCity',
      source: 'AddressBillingCity',
      label: 'City',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressBillingState',
      source: 'AddressBillingState',
      label: 'State',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressBillingCountry',
      source: 'AddressBillingCountry',
      label: 'Country',
      tab: 'address',
      addressSection: 'billing',
      span: 1,
    },
    {
      key: 'addressInstallZip',
      source: 'AddressInstallZip',
      label: 'Zip',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
      postalLookup: {
        streetKey: 'addressInstallStreet',
        districtKey: 'addressInstallDistrict',
        cityKey: 'addressInstallCity',
        stateKey: 'addressInstallState',
        countryKey: 'addressInstallCountry',
        numberKey: 'addressInstallNumber',
      },
    },
    {
      key: 'addressInstallStreet',
      source: 'AddressInstallStreet',
      label: 'Street',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
    },
    {
      key: 'addressInstallNumber',
      source: 'AddressInstallNumber',
      label: 'Number',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
    },
    {
      key: 'addressInstallDistrict',
      source: 'AddressInstallDistrict',
      label: 'District',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
    },
    {
      key: 'addressInstallCity',
      source: 'AddressInstallCity',
      label: 'City',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
    },
    {
      key: 'addressInstallState',
      source: 'AddressInstallState',
      label: 'State',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
    },
    {
      key: 'addressInstallCountry',
      source: 'AddressInstallCountry',
      label: 'Country',
      tab: 'address',
      addressSection: 'installation',
      span: 1,
    },
    {
      key: 'notes',
      source: 'Notes',
      label: 'Notes',
      type: 'textarea',
      tab: 'notes',
      span: 4,
      rows: 4,
    },
  ],
  addressSections: [
    { key: 'billing', label: 'Billing Address' },
    { key: 'installation', label: 'Installation Address' },
  ],
  addressCopyActions: [
    {
      key: 'installSameAsBilling',
      label: 'Same as billing address option',
      addressSection: 'installation',
      defaultEnabled: true,
      summaryLabel: 'Same as billing address',
      fromPrefix: 'addressBilling',
      toPrefix: 'addressInstall',
      fields: ['Zip', 'Street', 'Number', 'District', 'City', 'State', 'Country'],
    },
  ],
});

@Component({
  selector: 'app-invoicing-contracts',
  standalone: true,
  imports: CONFIGURABLE_CRUD_IMPORTS,
  templateUrl: '../../../../../shared/crud/configurable-crud/configurable-crud-page.html',
  styleUrls: ['../../../../../shared/crud/configurable-crud/configurable-crud-page.scss'],
})
export class InvoicingContractsPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> {
  constructor() {
    super(config);
  }

  protected override augmentPayload(payload: ConfigurableCrudRecord): ConfigurableCrudRecord {
    const next: ConfigurableCrudRecord = { ...payload };
    for (const [key, value] of Object.entries(next)) {
      if (typeof value === 'string' && !value.trim()) next[key] = null;
    }
    return {
      ...next,
      status: payload['status'],
      title: payload['title'],
      amount: Number(payload['amount']),
      installSameAsBilling: this.enabledCopyActions().has('installSameAsBilling'),
    };
  }
}
