import { Component } from '@angular/core';

import {
  DirectoryConfig,
  DirectoryCrudPageBase,
  DirectoryRecord,
  ERP_DIRECTORY_CRUD_IMPORTS,
} from '../shared/directory-crud/directory-crud-page-base';

const TYPE_OPTIONS = [
  { value: 'company', label: 'Company' },
  { value: 'person', label: 'Person' },
];

const CARRIER_CONFIG: DirectoryConfig = {
  endpoint: 'erp/carriers',
  uuidField: 'CarrierUUID',
  pageTitle: 'Carriers',
  pageDescription: 'Manage carriers and logistics contact data.',
  createTitle: 'New carrier',
  editTitle: 'Edit carrier',
  dialogDescription: 'Maintain carrier registration, contact and address data.',
  searchPlaceholder: 'Search',
  emptyLabel: 'No carriers found.',
  deleteTitle: 'Delete carrier',
  deleteMessage: 'Are you sure you want to delete this carrier?',
  deleteSelectedTitle: 'Delete selected carriers',
  deleteSelectedMessage: 'Delete {count} selected carriers?',
  savedMessage: 'Carrier saved successfully.',
  deletedMessage: 'Carrier deleted successfully.',
  deleteFailedMessage: 'Failed to delete carrier.',
  statusMode: 'number',
  activeValue: 1,
  inactiveValue: 0,
  initialValues: {
    status: 1,
    type: 'company',
    name: '',
    document: '',
    email: '',
    phone: '',
    street: '',
    number: '',
    district: '',
    complement: '',
    city: '',
    state: '',
    zip: '',
    country: '',
    notes: '',
  },
  columns: [
    { id: 'name', label: 'Name', kind: 'identity', field: 'Name', uuidField: 'CarrierUUID' },
    { id: 'type', label: 'Type', field: 'Type' },
    { id: 'document', label: 'Document', field: 'Document', className: 'document-col' },
    { id: 'email', label: 'E-mail', field: 'Email', className: 'email-col' },
    { id: 'status', label: 'Status', kind: 'status', field: 'Status', className: 'status-col' },
  ],
  fields: [
    {
      key: 'status',
      source: 'Status',
      payloadKey: 'status',
      label: 'Status',
      type: 'status',
      span: 1,
    },
    {
      key: 'type',
      source: 'Type',
      payloadKey: 'type',
      label: 'Type',
      type: 'select',
      options: TYPE_OPTIONS,
      span: 1,
    },
    { key: 'name', source: 'Name', payloadKey: 'name', label: 'Name', required: true, span: 2 },
    { key: 'document', source: 'Document', payloadKey: 'document', label: 'Document', span: 2 },
    { key: 'email', source: 'Email', payloadKey: 'email', label: 'E-mail', type: 'email', span: 1 },
    { key: 'phone', source: 'Phone', payloadKey: 'phone', label: 'Phone', type: 'phone', span: 1 },
    {
      key: 'zip',
      source: 'Zip',
      payloadKey: 'zip',
      label: 'Zip',
      tab: 'address',
      span: 1,
      postalLookup: {
        streetKey: 'street',
        districtKey: 'district',
        complementKey: 'complement',
        cityKey: 'city',
        stateKey: 'state',
        countryKey: 'country',
        numberKey: 'number',
      },
    },
    {
      key: 'street',
      source: 'Street',
      payloadKey: 'street',
      label: 'Street',
      tab: 'address',
      span: 1,
    },
    {
      key: 'number',
      source: 'Number',
      payloadKey: 'number',
      label: 'Number',
      tab: 'address',
      span: 1,
    },
    {
      key: 'district',
      source: 'District',
      payloadKey: 'district',
      label: 'District',
      tab: 'address',
      span: 1,
    },
    {
      key: 'complement',
      source: 'Complement',
      payloadKey: 'complement',
      label: 'Complement',
      tab: 'address',
      span: 1,
    },
    { key: 'city', source: 'City', payloadKey: 'city', label: 'City', tab: 'address', span: 1 },
    { key: 'state', source: 'State', payloadKey: 'state', label: 'State', tab: 'address', span: 1 },
    {
      key: 'country',
      source: 'Country',
      payloadKey: 'country',
      label: 'Country',
      tab: 'address',
      span: 1,
    },
    {
      key: 'notes',
      source: 'Notes',
      payloadKey: 'notes',
      label: 'Notes',
      type: 'textarea',
      tab: 'notes',
      span: 4,
      rows: 4,
    },
  ],
};

@Component({
  selector: 'app-erp-carrier',
  standalone: true,
  imports: ERP_DIRECTORY_CRUD_IMPORTS,
  templateUrl: '../shared/directory-crud/directory-crud-page.html',
  styleUrls: ['../shared/directory-crud/directory-crud-page.scss'],
})
export class ErpCarrierPage extends DirectoryCrudPageBase<DirectoryRecord> {
  constructor() {
    super(CARRIER_CONFIG);
  }
}
