import { Component } from '@angular/core';
import {
  CONFIGURABLE_CRUD_IMPORTS,
  ConfigurableCrudPageBase,
  ConfigurableCrudRecord,
  ConfigurableCrudRowAction,
  ConfigurableCrudSaveContext,
} from '../../../../shared/crud/configurable-crud/configurable-crud-page-base';
import { defineCrud } from '../../../../shared/crud/configurable-crud/define-crud';
import { quickCreateFor } from '../../../../shared/crud/configurable-crud/quick-create';
import { openDataViewerDialog } from '../../../../shared/data-viewer-dialog/data-viewer-dialog';

const ENDPOINT = 'erp/human-resources/time-clock/accounts';

const statuses = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'blocked', label: 'Blocked' },
];

type TemporaryCredential = {
  LoginCode?: string | null;
  TemporaryPassword?: string | null;
  TemporaryPasswordExpiresAt?: string | null;
};

// Pulse login credentials are generated by the API; the one-time password is shown once
// through the shared data viewer after create or reset and is never stored by the App.
const config = defineCrud({
  endpoint: ENDPOINT,
  uuidField: 'TimeClockAccountUUID',
  pageTitle: 'Time Clock Accounts',
  pageDescription: 'Generate secure Pulse access for HR employees.',
  searchPlaceholder: 'Employee or login code',
  emptyLabel: 'No time clock accounts found.',
  bulkDelete: true,
  statusMode: 'string',
  activeValue: 'active',
  inactiveValue: 'inactive',
  statusOptions: statuses,
  activeStatusValues: ['active'],
  initialValues: { status: 'active', employeeUUID: '', notes: '' },
  columns: [
    {
      id: 'employee',
      label: 'Employee',
      field: 'EmployeeName',
      uuidField: 'TimeClockAccountUUID',
      kind: 'identity',
    },
    {
      id: 'loginCode',
      label: 'Login code',
      field: 'LoginCode',
      translateValue: false,
      copyable: true,
    },
    { id: 'status', label: 'Status', field: 'Status', kind: 'status' },
    { id: 'temporary', label: 'Temporary', field: 'MustChangePassword', kind: 'boolean' },
    { id: 'lastLogin', label: 'Last login', field: 'LastLoginAt', kind: 'datetime' },
  ],
  fields: [
    {
      key: 'status',
      source: 'Status',
      label: 'Status',
      type: 'status',
      options: statuses,
      span: 1,
    },
    {
      key: 'employeeUUID',
      source: 'EmployeeUUID',
      label: 'Employee',
      type: 'search-select',
      required: true,
      remoteLookup: {
        endpoint: 'erp/human-resources/employees?status=1',
        uuidField: 'EmployeeUUID',
        labelField: 'Name',
        selectedLabelField: 'EmployeeName',
      },
      quickCreate: quickCreateFor('ErpHrEmployeeEmpUUID'),
      disabledWhen: ({ editing }) => editing,
      span: 1,
    },
    {
      key: 'notes',
      source: 'Notes',
      label: 'Notes',
      type: 'textarea',
      tab: 'notes',
      span: 4,
      rows: 4,
    },
  ],
  rowActions: [
    { key: 'resetPassword', label: 'Reset password', icon: 'key', tooltip: 'Reset password' },
  ],
});

@Component({
  selector: 'app-erp-hr-time-clock-accounts',
  standalone: true,
  imports: CONFIGURABLE_CRUD_IMPORTS,
  templateUrl: '../../../../shared/crud/configurable-crud/configurable-crud-page.html',
  styleUrls: ['../../../../shared/crud/configurable-crud/configurable-crud-page.scss'],
})
export class ErpHumanResourcesTimeClockAccountsPage extends ConfigurableCrudPageBase<ConfigurableCrudRecord> {
  constructor() {
    super(config);
  }

  protected override afterSave(context: ConfigurableCrudSaveContext<ConfigurableCrudRecord>): void {
    if (context.mode !== 'create') return;
    const credential = (context.response as { data?: TemporaryCredential } | null)?.data;
    if (credential?.TemporaryPassword) this.showCredential(credential);
  }

  override async handleRowAction(
    action: ConfigurableCrudRowAction,
    row: ConfigurableCrudRecord,
  ): Promise<void> {
    if (action.key !== 'resetPassword') return;
    const confirmed = await this.confirmAction(
      'Reset password',
      'Generate a new temporary password? The previous password stops working immediately.',
      'Reset password',
    );
    if (!confirmed) return;
    try {
      const response = await this.api.post<{ data?: TemporaryCredential }>(
        `${ENDPOINT}/${row['TimeClockAccountUUID']}/reset-password`,
        {},
      );
      this.snack.success(this.t('Temporary password generated successfully.'));
      this.refreshList();
      this.showCredential({ ...response?.data, LoginCode: String(row['LoginCode'] ?? '') });
    } catch (error) {
      this.snack.error(this.t(this.errorMessage(error) || 'Failed to reset password.'));
    }
  }

  private showCredential(credential: TemporaryCredential): void {
    openDataViewerDialog(this.dialog, {
      title: 'Temporary credentials',
      description:
        'Show these credentials to the employee securely. The password is not stored here.',
      details: [
        {
          label: 'Login code',
          value: credential.LoginCode ?? '',
          monospace: true,
          translate: false,
        },
        {
          label: 'Expires at',
          value: credential.TemporaryPasswordExpiresAt ?? '',
          kind: 'datetime',
        },
      ],
      sections: [
        {
          title: 'Temporary password',
          code: { value: credential.TemporaryPassword ?? '', format: 'text', copy: true },
        },
      ],
    });
  }
}
